package UAS;

import static UAS.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Made Artha
 * TGL 24 Mei 2025
 */
public class formNilai extends javax.swing.JFrame {
      DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form formBuku
     * @throws java.sql.SQLException
     */
    public formNilai() throws SQLException {
        initComponents();
        tblBuku.setModel(dtm);
        dtm.addColumn("nim");
        dtm.addColumn("nama");
        dtm.addColumn("Mata_Kuliah");
        dtm.addColumn("Nilai_Huruf");
         
       
        
        lsDtbuku();
        fieldEnabled(false);
        tombol(false);
        cBARU.setEnabled(true);
        cTUTUP.setEnabled(true);
        
        
    }
    private void fieldEnabled(boolean opsi){
    txID.setEditable(opsi);
    txNAMA.setEditable(opsi);
    txJUDUL.setEditable(opsi);
    txPENULIS.setEditable(opsi);}
    
    private void tombol(boolean opsi){
    cBARU.setEnabled(opsi);
    cUBAH.setEnabled(opsi);
    cHAPUS.setEnabled(opsi);
    cTUTUP.setEnabled(opsi);
    }
     private void clearForm(){
         txID.setText("");
         txNAMA.setText("");
         txPENULIS.setText("");
         txJUDUL.setText("");
     }
    private void lsDtbuku() throws SQLException{
      Connection cnn = koneksi();
      dtm.getDataVector().removeAllElements();
      dtm.fireTableDataChanged();
      if( !cnn.isClosed() ){
          PreparedStatement ps = cnn.prepareStatement("SELECT * FROM nilai;");
          ResultSet rs = ps.executeQuery();
          while( rs.next() ){
              Object[] dta = new Object[4];
              dta[0] = rs.getString("nim");
              dta[1] = rs.getString("nama_mahasiswa");
               dta[2] = rs.getString("mata_kuliah");
              dta[3] = rs.getString("nilai_huruf");
             
              
            dtm.addRow(dta);
          
          }
          cnn.close();
    }
    }
    private void storeData() throws SQLException {
    Connection cnn = koneksi();
    if (!cnn.isClosed()) {
        PreparedStatement ps = cnn.prepareStatement("INSERT INTO nilai (nim, nama_mahasiswa, mata_kuliah, nilai_huruf) VALUES (?, ?, ?, ?);");
        ps.setString(1, txID.getText());
        ps.setString(2, txNAMA.getText());
        ps.setString(3, txJUDUL.getText());
        ps.setString(4, txPENULIS.getText());
        ps.executeUpdate();
        cnn.close();
    }
}

 private void updateData() throws SQLException {
    Connection cnn = koneksi();
    if (!cnn.isClosed()) {
        PreparedStatement ps = cnn.prepareStatement("UPDATE nilai SET nama_mahasiswa=?, mata_kuliah=?, nilai_huruf=? WHERE nim=?;");
        ps.setString(1, txNAMA.getText());
        ps.setString(2, txJUDUL.getText());
        ps.setString(3, txPENULIS.getText());
        ps.setString(4, txID.getText());
        ps.executeUpdate();
        cnn.close();
    }
}


    private void destoryData() throws SQLException {
    Connection cnn = koneksi();
    if (!cnn.isClosed()) {
        PreparedStatement ps = cnn.prepareStatement("DELETE FROM nilai WHERE nim=?;");
        ps.setString(1, txID.getText());
        ps.executeUpdate();
        cnn.close();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txNim = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        txNama = new javax.swing.JLabel();
        txNAMA = new javax.swing.JTextField();
        txMK = new javax.swing.JLabel();
        txJUDUL = new javax.swing.JTextField();
        txNilai = new javax.swing.JLabel();
        txPENULIS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        cBARU = new javax.swing.JButton();
        cUBAH = new javax.swing.JButton();
        cHAPUS = new javax.swing.JButton();
        cTUTUP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("APLIKASI DATA NILAI");

        txNim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txNim.setText("Nim");

        txID.setBackground(new java.awt.Color(204, 255, 255));
        txID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txID.setForeground(new java.awt.Color(0, 204, 204));

        txNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txNama.setText("Nama");

        txNAMA.setBackground(new java.awt.Color(204, 255, 255));
        txNAMA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txNAMA.setForeground(new java.awt.Color(153, 255, 255));

        txMK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txMK.setText("Mata Kuliah");

        txJUDUL.setBackground(new java.awt.Color(204, 255, 255));
        txJUDUL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txNilai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txNilai.setText("Nilai");

        txPENULIS.setBackground(new java.awt.Color(204, 255, 255));
        txPENULIS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuku);

        cBARU.setBackground(new java.awt.Color(0, 153, 204));
        cBARU.setText("Baru");
        cBARU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBARUActionPerformed(evt);
            }
        });

        cUBAH.setBackground(new java.awt.Color(0, 153, 204));
        cUBAH.setText("Ubah");
        cUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUBAHActionPerformed(evt);
            }
        });

        cHAPUS.setBackground(new java.awt.Color(0, 153, 204));
        cHAPUS.setText("Hapus");
        cHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHAPUSActionPerformed(evt);
            }
        });

        cTUTUP.setBackground(new java.awt.Color(0, 153, 204));
        cTUTUP.setText("Tutup");
        cTUTUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTUTUPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txNama)
                                    .addComponent(txMK)
                                    .addComponent(txNilai)
                                    .addComponent(txNim))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txJUDUL, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txPENULIS, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(cBARU)
                        .addGap(18, 18, 18)
                        .addComponent(cUBAH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cHAPUS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cTUTUP))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1)))
                .addContainerGap(520, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNim)
                    .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txMK)
                    .addComponent(txJUDUL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNilai))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txPENULIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBARU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cUBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cHAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTUTUP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHAPUSActionPerformed
         if (!txID.getText().equals("")) {
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Yakin ingin menghapus data ini?", 
            "Konfirmasi Hapus", 
            JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                destoryData();          // Jalankan perintah hapus di database
                //sAplikasiNilai();             // Refresh tabel
                lsDtbuku();
                clearForm();            // Kosongkan form input
                fieldEnabled(false);    // Nonaktifkan field input
                tombol(false);          // Nonaktifkan tombol aksi
                cBARU.setEnabled(true);
                
                cTUTUP.setEnabled(true);
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
            } catch (SQLException ex) {
                Logger.getLogger(formNilai.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin dihapus terlebih dahulu.");
    }
    }//GEN-LAST:event_cHAPUSActionPerformed

    private void cTUTUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTUTUPActionPerformed
       int opsi = JOptionPane.showOptionDialog(this, "Yakin akan Menup Form", "Konfirmasi Tutup Form", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(opsi == JOptionPane.YES_OPTION)
        System.exit(0);
        
       
    }//GEN-LAST:event_cTUTUPActionPerformed

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
        int row = tblBuku.getSelectedRow();

        txID.setText(tblBuku.getValueAt(row, 0).toString());
        txNAMA.setText(tblBuku.getValueAt(row, 1).toString());
        txJUDUL.setText(tblBuku.getValueAt(row, 2).toString());
        txPENULIS.setText(tblBuku.getValueAt(row, 3).toString());

        cUBAH.setEnabled(true);
        cHAPUS.setEnabled(true);

    }//GEN-LAST:event_tblBukuMouseClicked

    private void cBARUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBARUActionPerformed
       if(cBARU.getText().equals("Baru")){
           cBARU.setText("Simpan");
           cTUTUP.setText("Batal");
           cUBAH.setEnabled(false);
           cHAPUS.setEnabled(false);
           clearForm();
           fieldEnabled(true);
       }else{
           if(!txID.getText().equals("")){
               try {
                   storeData();
                   lsDtbuku();
               } catch (SQLException ex) {
                   Logger.getLogger(formNilai.class.getName()).log(Level.SEVERE, null, ex);
               }
           }
           cBARU.setText("Baru");
           cTUTUP.setText("Tutup");
           clearForm();
           fieldEnabled(false);
           
       }
    }//GEN-LAST:event_cBARUActionPerformed

    private void cUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUBAHActionPerformed
         if (!txID.getText().equals("")) {
        fieldEnabled(true); // ✅ Aktifkan semua field supaya bisa diketik dulu
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menyimpan perubahan data ini?", "Konfirmasi Ubah", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                updateData();            // simpan ke database
                lsDtbuku();              // refresh tabel
                clearForm();             // kosongkan form
                fieldEnabled(false);     // kunci kembali field
                tombol(false);           // matikan tombol
                cBARU.setEnabled(true);  // aktifkan tombol Baru
                cTUTUP.setEnabled(true); // aktifkan tombol Tutup
                JOptionPane.showMessageDialog(this, "Data berhasil diubah.");
            } catch (SQLException ex) {
                Logger.getLogger(formNilai.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengubah data.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin diubah terlebih dahulu.");
    }
    }//GEN-LAST:event_cUBAHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new formNilai().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(formNilai.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBARU;
    private javax.swing.JButton cHAPUS;
    private javax.swing.JButton cTUTUP;
    private javax.swing.JButton cUBAH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txJUDUL;
    private javax.swing.JLabel txMK;
    private javax.swing.JTextField txNAMA;
    private javax.swing.JLabel txNama;
    private javax.swing.JLabel txNilai;
    private javax.swing.JLabel txNim;
    private javax.swing.JTextField txPENULIS;
    // End of variables declaration//GEN-END:variables

    private Object tblNilaiSelectedRow(JTable tblNilai) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
